version: "3.3"

services:
  mongodb:
    image: mongo:5.0.3
    container_name: mongo
    restart: always
    volumes:
     - ./dockercache/mongoData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend:
    image: node:16.13.0
    container_name: backend
    user: node
    depends_on:
      - mongodb
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    expose:
      - "3000"
    ports:
      - 3000:3000
    command: "yarn start"

  frontend:
    image: node:16.13.0
    container_name: frontend
    user: node
    depends_on:
      - mongodb
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - "4200"
    ports:
      - 4200:4200
    command: "yarn start"